# This file was generated by GoReleaser. DO NOT EDIT.
cask "assign" do
  version "0.1.0-preview.1"

  on_macos do
    on_intel do
      sha256 "4f21039a6cbcd5417c101198e6411447a73cd6508ca28c6b777c36feacb30d79"
      url "https://github.com/assignso/homebrew-tap/releases/download/v#{version}/assign_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6af30a570a17f27ab2426000055a839230479e1d470490240f8bac729bb1ebf"
      url "https://github.com/assignso/homebrew-tap/releases/download/v#{version}/assign_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "356be0699453f32dd140f1f36f2da344423a24fb1a4c0394e03b45960db73aab"
      url "https://github.com/assignso/homebrew-tap/releases/download/v#{version}/assign_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98bff23b71f0a4c0364a78c753df4a3f3f6e65f1c24cb0fa9ab59991165dd7de"
      url "https://github.com/assignso/homebrew-tap/releases/download/v#{version}/assign_#{version}_linux_arm64.tar.gz"
    end
  end

  name "assign"
  desc "Work with Assign from the terminal"
  homepage "https://assign.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "assign"

  # No zap stanza required

end
